import { type AppRole, ROLES } from "@/lib/rbac/roles";

export const PERMISSIONS = {
  USERS_VIEW: "users.view",
  USERS_CREATE: "users.create",
  USERS_EDIT: "users.edit",
  USERS_DELETE: "users.delete",
  ROLES_MANAGE: "roles.manage",
  SETTINGS_MANAGE: "settings.manage",
  CUSTOMERS_VIEW_ALL: "customers.view_all",
  CUSTOMERS_VIEW_ASSIGNED: "customers.view_assigned",
  CUSTOMERS_CREATE: "customers.create",
  CUSTOMERS_EDIT: "customers.edit",
  VENDORS_VIEW_ALL: "vendors.view_all",
  VENDORS_VIEW_OWN: "vendors.view_own",
  VENDORS_EDIT_OWN: "vendors.edit_own",
  DESIGNERS_VIEW_ALL: "designers.view_all",
  DESIGNERS_VIEW_ASSIGNED: "designers.view_assigned",
  REFERRALS_VIEW_ALL: "referrals.view_all",
  REFERRALS_VIEW_OWN: "referrals.view_own",
  RESELLERS_VIEW_ALL: "resellers.view_all",
  RESELLERS_VIEW_OWN: "resellers.view_own",
  EMPLOYEES_VIEW: "employees.view",
  EMPLOYEES_MANAGE: "employees.manage",
  PROJECTS_VIEW_ALL: "projects.view_all",
  PROJECTS_VIEW_ASSIGNED: "projects.view_assigned",
  PROJECTS_CREATE: "projects.create",
  PROJECTS_EDIT: "projects.edit",
  ORDERS_VIEW_ALL: "orders.view_all",
  ORDERS_VIEW_ASSIGNED: "orders.view_assigned",
  ORDERS_CREATE: "orders.create",
  ORDERS_EDIT: "orders.edit",
  QUOTES_VIEW: "quotes.view",
  QUOTES_CREATE: "quotes.create",
  QUOTES_EDIT: "quotes.edit",
  INVOICES_VIEW: "invoices.view",
  INVOICES_CREATE: "invoices.create",
  INVOICES_EDIT: "invoices.edit",
  MESSAGES_VIEW: "messages.view",
  MESSAGES_SEND: "messages.send",
  NOTIFICATIONS_VIEW: "notifications.view",
  FILES_VIEW: "files.view",
  FILES_UPLOAD: "files.upload",
  PROFILE_VIEW: "profile.view",
  PROFILE_EDIT: "profile.edit",
  REPORTS_VIEW: "reports.view",
  ACTIVITY_VIEW: "activity.view",
} as const;

export type Permission = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];

const everyonePermissions = [
  PERMISSIONS.PROFILE_VIEW,
  PERMISSIONS.PROFILE_EDIT,
  PERMISSIONS.MESSAGES_VIEW,
  PERMISSIONS.MESSAGES_SEND,
  PERMISSIONS.NOTIFICATIONS_VIEW,
  PERMISSIONS.FILES_VIEW,
] as const satisfies readonly Permission[];

const employeeOperationsPermissions = [
  PERMISSIONS.CUSTOMERS_VIEW_ASSIGNED,
  PERMISSIONS.CUSTOMERS_EDIT,
  PERMISSIONS.ORDERS_VIEW_ASSIGNED,
  PERMISSIONS.ORDERS_EDIT,
  PERMISSIONS.PROJECTS_VIEW_ASSIGNED,
  PERMISSIONS.PROJECTS_EDIT,
  PERMISSIONS.QUOTES_VIEW,
  PERMISSIONS.QUOTES_EDIT,
  PERMISSIONS.FILES_UPLOAD,
] as const satisfies readonly Permission[];

const superAdminPermissions = Object.values(PERMISSIONS);

export const ROLE_PERMISSIONS: Record<AppRole, readonly Permission[]> = {
  [ROLES.SUPER_ADMIN]: superAdminPermissions,
  [ROLES.ADMIN]: superAdminPermissions,
  [ROLES.EMPLOYEE]: [...everyonePermissions, ...employeeOperationsPermissions, PERMISSIONS.EMPLOYEES_VIEW, PERMISSIONS.ACTIVITY_VIEW],
  [ROLES.STAFF]: [...everyonePermissions, ...employeeOperationsPermissions, PERMISSIONS.EMPLOYEES_VIEW, PERMISSIONS.ACTIVITY_VIEW],
  [ROLES.PRODUCTION_MANAGER]: [...everyonePermissions, ...employeeOperationsPermissions, PERMISSIONS.PROJECTS_CREATE, PERMISSIONS.ACTIVITY_VIEW],
  [ROLES.INSTALLER]: [...everyonePermissions, PERMISSIONS.ORDERS_VIEW_ASSIGNED, PERMISSIONS.PROJECTS_VIEW_ASSIGNED, PERMISSIONS.PROJECTS_EDIT, PERMISSIONS.FILES_UPLOAD],
  [ROLES.CUSTOMER_SUPPORT]: [...everyonePermissions, PERMISSIONS.CUSTOMERS_VIEW_ASSIGNED, PERMISSIONS.CUSTOMERS_EDIT, PERMISSIONS.ORDERS_VIEW_ASSIGNED, PERMISSIONS.MESSAGES_SEND],
  [ROLES.CUSTOMER]: [
    ...everyonePermissions,
    PERMISSIONS.ORDERS_VIEW_ASSIGNED,
    PERMISSIONS.ORDERS_CREATE,
    PERMISSIONS.PROJECTS_VIEW_ASSIGNED,
    PERMISSIONS.PROJECTS_CREATE,
    PERMISSIONS.QUOTES_CREATE,
    PERMISSIONS.INVOICES_VIEW,
    PERMISSIONS.FILES_UPLOAD,
  ],
  [ROLES.VENDOR]: [
    ...everyonePermissions,
    PERMISSIONS.VENDORS_VIEW_OWN,
    PERMISSIONS.VENDORS_EDIT_OWN,
    PERMISSIONS.ORDERS_VIEW_ASSIGNED,
    PERMISSIONS.PROJECTS_VIEW_ASSIGNED,
    PERMISSIONS.QUOTES_VIEW,
    PERMISSIONS.FILES_UPLOAD,
  ],
  [ROLES.DESIGNER]: [
    ...everyonePermissions,
    PERMISSIONS.DESIGNERS_VIEW_ASSIGNED,
    PERMISSIONS.CUSTOMERS_VIEW_ASSIGNED,
    PERMISSIONS.ORDERS_VIEW_ASSIGNED,
    PERMISSIONS.PROJECTS_VIEW_ASSIGNED,
    PERMISSIONS.PROJECTS_EDIT,
    PERMISSIONS.FILES_UPLOAD,
  ],
  [ROLES.REFERRAL]: [
    ...everyonePermissions,
    PERMISSIONS.REFERRALS_VIEW_OWN,
    PERMISSIONS.CUSTOMERS_VIEW_ASSIGNED,
  ],
  [ROLES.RESELLER]: [
    ...everyonePermissions,
    PERMISSIONS.RESELLERS_VIEW_OWN,
    PERMISSIONS.CUSTOMERS_VIEW_ASSIGNED,
    PERMISSIONS.CUSTOMERS_CREATE,
    PERMISSIONS.ORDERS_VIEW_ASSIGNED,
    PERMISSIONS.PROJECTS_VIEW_ASSIGNED,
    PERMISSIONS.REPORTS_VIEW,
  ],
};
